name: Coverage
on:
  push:
    branches: [ "main" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          flit install --extras coverage
      - name: Run tests and collect coverage
        run: pytest --cov robinwould
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
